#!/bin/bash

# true = Le backup sera effectué.
# false = Le backup ne sera pas effectué.
enabled=false

# Chemin vers le répertoire dans lequel seront stockés les backup.
repository_path=/mnt/backup/abc-archives

# Le nom de l'archive à créer, préfixé par la date courante.
# Format de la date par défaut : jj-mm-aaaa~hh:mm
# Pour un nom d'archive contenant uniquement la date, mettre `archive_name` en commentaire.
current_date="-$(date +%d-%m-%Y~%H:%M)"
archive_name=abc

# Le niveau de compression souhaité.
compression=zlib

# Les fichiers et répertoires à sauvegarder.
# Il est important d'indiquer les chemins complets depuis la racine du système.
to_save=(/home /etc)

if [ "$enabled" = true ]; then
    . "$(dirname "$(readlink -f "$0")")/../add-backup"
fi

#==================================================================================================================
# Pour faire d'autres backup il suffit de faire une copie de ce fichier avec un nouveau nom dans le même répertoire
# et de modifier les valeurs des variables selon les besoins du nouveau backup.
#
# Chaque fichier est autonome et correspond ainsi à l'un des backup nécessaires.
# Vous pouvez l'exécuter en directe, ou bien l'automatiser selon les besoins.
#
# Pour automatiser chaque backup, il est possible d'ajouter une ligne dans crontab.
# Exemple pour ce fichier : * 12 * * * /chemin/vers/SaveMe/backups/whd
#
# ATTENTION : Pour des raisons de sécurité et de compatibilité, il est impératif que les scripts contenus dans SaveMe
# soient utilisé en tant que root.
#======================================================
